[package]
name = "ecr-image-browser"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }
structopt = "0.3.26"
aws-config = "1.5.4"
aws-sdk-ecr = "1.34.0"
